name: gp2
description: "Graduation Project for Universtiy Of Petra"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  http: ^1.4.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  qr_flutter: ^4.0.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  flutter_gen: ^5.10.0
  intl: ^0.19.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - images/
    - assets/
    - assets/logo.svg